
const projects = ([

  {
    id: "01",
    name: "Estudio de Grabación Norte",
    slug: "estudio-de-grabacion-norte",
    category: "acond",
    client: "SAYCO Bogotá",
    city: "Bogotá",
    country: "Colombia",
    date: "2018-11-14 12:00",
    tagline: "Un espacio que vibra con estilo",
    description:
      "Uismodolor, utpat erci a lam tis os, quip lummy, uipsuscidunt iusto nullandrem. Veliquam amconul veriliquat, is erciduisit molor tetummy na wisl laore sisi. Dionsenim to ate dolorem molor adiam. Enim ptatueros wiscip nissectet iurerosto veliquisl do eum, atum. Atum quis ptatueros eraessit utpat, esed vullutat, ud nisci. Conse ncidui augiametuer conullam quis ptatueros modit, minisl, ed essequating a digniamet. Esse ullam del aliquipsusci nismodit, dolutatueros te amconul tio veleniat tie. Scillummy ver at. Feu eniatisit tionsequisim tio lummy it, dolortionum it. Iriustrud ero ros molent. Ullum diat nim modit. Eu lam hendrem esse duis.",
    mainImage: "/images/projects/proyecto4-1.jpeg",
    imgUrl1: "/images/projects/proyecto4-2.jpeg",
    imgUrl2: "/images/projects/proyecto4-3.jpeg",
    imgUrl3: "/images/projects/proyecto4-4.jpeg",
    imgUrl4: "/images/projects/proyecto4-5.jpeg",
    attribute1Name: "Tiempo de Ejecución",
    attribute1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit.",
    attribute2Name: "Técnica de Acondicionamiento ",
    attribute2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit.",
    attribute3Name: "Elementos Instalados",
    attribute3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit. Atum quis ptatueros eraessit utpat, esed vullutat, ud nisci. Conse ncidui augiametuer conullam quis ptatueros modit, minisl, ed essequating a digniamet. Esse ullam del aliquipsusci nismodit."
  },
  {
    id: "02",
    name: "Estudio Pablo Iglesia",
    slug: "estudio-pablo-iglesia",
    category: "aisla",
    client: "Pablo Iglesia",
    city: "Bogotá",
    country: "Colombia",
    date: "2018-11-14 12:00",
    tagline: "Un espacio que vibra con estilo",
    description:
      "Uismodolor, utpat erci a lam tis os, quip lummy, uipsuscidunt iusto nullandrem. Veliquam amconul veriliquat, is erciduisit molor tetummy na wisl laore sisi. Dionsenim to ate dolorem molor adiam. Enim ptatueros wiscip nissectet iurerosto veliquisl do eum, atum. Atum quis ptatueros eraessit utpat, esed vullutat, ud nisci. Conse ncidui augiametuer conullam quis ptatueros modit, minisl, ed essequating a digniamet. Esse ullam del aliquipsusci nismodit, dolutatueros te amconul tio veleniat tie. Scillummy ver at. Feu eniatisit tionsequisim tio lummy it, dolortionum it. Iriustrud ero ros molent. Ullum diat nim modit. Eu lam hendrem esse duis.",
    mainImage: "/images/projects/proyecto3-1.jpeg",
    imgUrl1: "/images/projects/proyecto3-2.jpeg",
    imgUrl2: "/images/projects/proyecto3-3.jpeg",
    imgUrl3: "/images/projects/proyecto3-4.jpeg",
    imgUrl4: "/images/projects/proyecto3-5.jpeg",
    attribute1Name: "Tiempo de Ejecución",
    attribute1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit.",
    attribute2Name: "Técnica de Acondicionamiento ",
    attribute2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit.",
    attribute3Name: "Elementos Instalados",
    attribute3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit. Atum quis ptatueros eraessit utpat, esed vullutat, ud nisci. Conse ncidui augiametuer conullam quis ptatueros modit, minisl, ed essequating a digniamet. Esse ullam del aliquipsusci nismodit."
  },
  {
    id: "03",
    name: "Estudio Renderella",
    slug: "renderella-studio",
    category: "acond",
    client: "Renderella Studios",
    city: "Bogotá",
    country: "Colombia",
    date: "2018-11-14 12:00",
    tagline: "Un espacio que vibra con estilo",
    description:
      "Uismodolor, utpat erci a lam tis os, quip lummy, uipsuscidunt iusto nullandrem. Veliquam amconul veriliquat, is erciduisit molor tetummy na wisl laore sisi. Dionsenim to ate dolorem molor adiam. Enim ptatueros wiscip nissectet iurerosto veliquisl do eum, atum. Atum quis ptatueros eraessit utpat, esed vullutat, ud nisci. Conse ncidui augiametuer conullam quis ptatueros modit, minisl, ed essequating a digniamet. Esse ullam del aliquipsusci nismodit, dolutatueros te amconul tio veleniat tie. Scillummy ver at. Feu eniatisit tionsequisim tio lummy it, dolortionum it. Iriustrud ero ros molent. Ullum diat nim modit. Eu lam hendrem esse duis.",
    mainImage: "/images/projects/proyecto2-2.jpeg",
    imgUrl1: "/images/projects/proyecto2-1.jpeg",
    imgUrl2: "/images/projects/proyecto2-5.jpeg",
    imgUrl3: "/images/projects/proyecto2-4.jpeg",
    imgUrl4: "/images/projects/proyecto2-3.jpeg",
    attribute1Name: "Tiempo de Ejecución",
    attribute1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit.",
    attribute2Name: "Técnica de Acondicionamiento ",
    attribute2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit.",
    attribute3Name: "Elementos Instalados",
    attribute3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit. Atum quis ptatueros eraessit utpat, esed vullutat, ud nisci. Conse ncidui augiametuer conullam quis ptatueros modit, minisl, ed essequating a digniamet. Esse ullam del aliquipsusci nismodit."
  },
  {
    id: "04",
    name: "Estudio rendercitos",
    slug: "rendersitos-estudios",
    category: "acond",
    client: "Estudios de audio profesional",
    city: "Bogotá",
    country: "Colombia",
    date: "2020-11-14 12:00",
    tagline: "Un espacio que vibra con estilo",
    description:
      "Uismodolor, utpat erci a lam tis os, quip lummy, uipsuscidunt iusto nullandrem. Veliquam amconul veriliquat, is erciduisit molor tetummy na wisl laore sisi. Dionsenim to ate dolorem molor adiam. Enim ptatueros wiscip nissectet iurerosto veliquisl do eum, atum. Atum quis ptatueros eraessit utpat, esed vullutat, ud nisci. Conse ncidui augiametuer conullam quis ptatueros modit, minisl, ed essequating a digniamet. Esse ullam del aliquipsusci nismodit, dolutatueros te amconul tio veleniat tie. Scillummy ver at. Feu eniatisit tionsequisim tio lummy it, dolortionum it. Iriustrud ero ros molent. Ullum diat nim modit. Eu lam hendrem esse duis.",
    mainImage: "/images/projects/proyecto1-1.jpeg",
    imgUrl1: "/images/projects/proyecto1-2.jpeg",
    imgUrl2: "/images/projects/proyecto1-3.jpeg",
    imgUrl3: "/images/projects/proyecto1-4.jpeg",
    imgUrl4: "/images/projects/proyecto1-5.jpeg",
    attribute1Name: "Tiempo de Ejecución",
    attribute1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit.",
    attribute2Name: "Técnica de Acondicionamiento ",
    attribute2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit.",
    attribute3Name: "Elementos Instalados",
    attribute3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit. Atum quis ptatueros eraessit utpat, esed vullutat, ud nisci. Conse ncidui augiametuer conullam quis ptatueros modit, minisl, ed essequating a digniamet. Esse ullam del aliquipsusci nismodit."
  },
  {
    id: "05",
    name: "Estudio 5",
    slug: "estudio-5",
    category: "aisla",
    client: "Palosanto Studios",
    city: "Bogotá",
    country: "Colombia",
    date: "2018-11-14 12:00",
    tagline: "Un espacio que vibra con estilo",
    description:
      "Uismodolor, utpat erci a lam tis os, quip lummy, uipsuscidunt iusto nullandrem. Veliquam amconul veriliquat, is erciduisit molor tetummy na wisl laore sisi. Dionsenim to ate dolorem molor adiam. Enim ptatueros wiscip nissectet iurerosto veliquisl do eum, atum. Atum quis ptatueros eraessit utpat, esed vullutat, ud nisci. Conse ncidui augiametuer conullam quis ptatueros modit, minisl, ed essequating a digniamet. Esse ullam del aliquipsusci nismodit, dolutatueros te amconul tio veleniat tie. Scillummy ver at. Feu eniatisit tionsequisim tio lummy it, dolortionum it. Iriustrud ero ros molent. Ullum diat nim modit. Eu lam hendrem esse duis.",
    mainImage: "/images/projects/estudio1.jpg",
    imgUrl1: "/images/projects/estudio1.jpg",
    imgUrl2: "/images/projects/estudio2.jpg",
    imgUrl3: "/images/projects/estudio3.jpg",
    imgUrl4: "/images/projects/estudio4.jpg",
    attribute1Name: "Tiempo de Ejecución",
    attribute1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit.",
    attribute2Name: "Técnica de Acondicionamiento ",
    attribute2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit.",
    attribute3Name: "Elementos Instalados",
    attribute3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Posuere nisi vel ornare aliquet. Eget blandit. Atum quis ptatueros eraessit utpat, esed vullutat, ud nisci. Conse ncidui augiametuer conullam quis ptatueros modit, minisl, ed essequating a digniamet. Esse ullam del aliquipsusci nismodit."
  }

]);

export default projects;
